# Generated by Django 5.2.5 on 2025-08-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('is_completed', models.BooleanField(default=False)),
                ('createdd_at', models.DateTimeField(auto_now_add=True)),
                ('upadetd_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
